# Generated by Django 6.0 on 2026-01-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.CharField(choices=[('January 2026', 'January 2026'), ('February 2026', 'February 2026'), ('March 2026', 'March 2026'), ('April 2026', 'April 2026'), ('May 2026', 'May 2026'), ('June 2026', 'June 2026'), ('July 2026', 'July 2026'), ('August 2026', 'August 2026'), ('September 2026', 'September 2026'), ('October 2026', 'October 2026'), ('November 2026', 'November 2026'), ('December 2026', 'December 2026')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancepayment',
            name='month',
            field=models.CharField(choices=[('January 2026', 'January 2026'), ('February 2026', 'February 2026'), ('March 2026', 'March 2026'), ('April 2026', 'April 2026'), ('May 2026', 'May 2026'), ('June 2026', 'June 2026'), ('July 2026', 'July 2026'), ('August 2026', 'August 2026'), ('September 2026', 'September 2026'), ('October 2026', 'October 2026'), ('November 2026', 'November 2026'), ('December 2026', 'December 2026')], max_length=20),
        ),
    ]
