# Generated by Django 6.0 on 2026-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_month_alter_maintenancepayment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancepayment',
            name='receipt',
            field=models.URLField(blank=True),
        ),
    ]
