# Generated by Django 6.0 on 2026-01-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_bill_alter_maintenancepayment_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='bill',
            new_name='bill_url',
        ),
        migrations.RenameField(
            model_name='maintenancepayment',
            old_name='receipt',
            new_name='receipt_url',
        ),
    ]
