# Generated by Django 6.0 on 2026-01-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_bill_expense_bill_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancepayment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
